version: '3'
services:

  certificate_renewal:
    image: gw2efficiency/certificate_renewal
    build:
      context: .
      dockerfile: _devops/certificate_renewal/Dockerfile
    restart: always
    volumes:
      - '/data/letsencrypt:/etc/letsencrypt'

  loadbalancing:
    image: gw2efficiency/loadbalancing
    build:
      context: .
      dockerfile: _devops/loadbalancing/Dockerfile
    restart: always
    depends_on:
      - api
      - static
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/data/letsencrypt:/etc/letsencrypt'

  api:
    image: gw2efficiency/api
    build:
      context: .
      dockerfile: _devops/api/Dockerfile
    depends_on:
      - mongodb
    env_file: secrets.env
    environment:
      MONGO_HOST: mongodb
    restart: always
    deploy:
      mode: replicated
      replicas: 12
      update_config:
        parallelism: 4
        delay: 3s
        monitor: 10s

  worker:
    image: gw2efficiency/worker
    build:
      context: .
      dockerfile: _devops/api/Dockerfile
    depends_on:
      - mongodb
    env_file: secrets.env
    environment:
      MONGO_HOST: mongodb
    restart: always
    deploy:
      mode: replicated
      replicas: 64
      update_config:
        parallelism: 16
        delay: 3s
        monitor: 10s

  static:
    image: gw2efficiency/static
    build:
      context: .
      dockerfile: _devops/static/Dockerfile
    restart: always

  mongodb:
    image: mongo:3.4
    restart: always
    volumes:
      - '/data/mongodb/configdb:/data/configdb'
      - '/data/mongodb/db:/data/db'

  redis:
    image: redis:3.2-alpine
    restart: always
